import Head from "next/head";
import Content from "../components/Content/Content";

// export default function Home({ tweets }) {
export default function Home() {
  return (
    <>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/twitter.ico" />
      </Head>
      <Content />
    </>
  );
}
