import Head from "next/head";
import { useEffect, useState } from "react";
import Content from "../components/Content/Content";
import { Tweets } from "../functions/fetchData";

// export const getServerSideProps = async () => {
//   const tweets = await Tweets();
//   return {
//     props: { tweets },
//   };
// };

// export default function Home({ tweets }) {
export default function Home() {
  const [myTweets, setMyTweets] = useState([]);
  useEffect(async () => {
    const tweets = await Tweets();
    setMyTweets(tweets);
  }, []);
  return (
    <>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/twitter.ico" />
      </Head>
      <Content tweets={myTweets} />
    </>
  );
}
